export enum AuthActionTypes {
  GET_CURRENT_USER = 'GET_CURRENT_USER',

  SIGNIN_REQUEST = 'SIGNIN_REQUEST',
  SIGNIN_SUCCESS = 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE = 'SIGNIN_FAILURE',

  SIGNOUT_REQUEST = 'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE = 'SIGNOUT_FAILURE',
}
export enum ProfileActionTypes {
  CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST',
  CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS',
  CREATE_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE',
}

export enum DashboardActionTypes {
  SET_COMPONENT = 'SET_COMPONENT',
  SET_EXPAND = 'SET_EXPAND',
  SET_THEME = 'SET_THEME',
  TOGGLE_MODE = 'TOGGLE_MODE',
}

export enum ModalActionTypes {
  TOGGLE_MODAL = 'TOGGLE_MODAL',
}

export enum NavActionTypes {
  TOGGLE_NAV = 'TOGGLE_NAV',
}
