export enum AuthActionTypes {
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  RESET_ERRORS = 'RESET_ERRORS',

  SIGNIN_REQUEST = 'SIGNIN_REQUEST',
  SIGNIN_SUCCESS = 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE = 'SIGNIN_FAILURE',

  SIGNOUT_REQUEST = 'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE = 'SIGNOUT_FAILURE',
}
export enum ModalActionTypes {
  TOGGLE_MODAL = 'TOGGLE_MODAL',
}

export enum NavActionTypes {
  TOGGLE_NAV = 'TOGGLE_NAV',
}
